#!/usr/bin/perl -w
use strict;

#phrap
#my $seq = "AACGGGCGCGCCGGCCCCAACGGGCGCGCCGGCGCGTTCGGGCGCGCCGGCCCGCCGGGCCGCTTCGGGCGCGCCGGCCGCCCGGCCCCAACGGGCGCGCCGGGCCGTTCGGGCGCGCCGGCCGCCCGGCCCGAACGGGCGCGCCGGCCCGCCGGGCCGCTTCGGGCGCGCCGGCGGCTTCGGGCGCGCCGGCCCCAACGGGCGCGCCGGCCGG";

#gap5 manual
my $seq = "ACGGGCGCGCCGGCCCCAACGGGCGCGCCGGCGCGTTCGGGCGCGCCGGCCCGCCGGGCCGTTCGGGCGCGCCGGCCGCCCGGCCCCAACGGGCGCGCCGGGCCGTTCGGGCGCGCCGGCCGCCCGGCCCGAACGGGCGCGCCGGCCCGCCGGCCGCTTCGGGCGCGCCGGCGGCTTCGGGCGCGCCGGCCCCAACGGGCGCGCCGGCCGGAACGGGCGCGCCGGCCCGCCGGCCGGAACGGGCGCGCCGGCCCGCCGGCGCGAACGGGCGCGCCGGCCCGCCGGCGGGTTCGGGCGCGCCGGCCCGCCGGCGCC";

while ($seq =~ m/((?:AA|TT)[^AT]*)/g) {
    $_=$1;
    #print;
    if (/AA/) {
	print ">";
    } else {
	print "<";
    }

    $_=substr($_,2);
    foreach (m/......../g) {
	#print "$_\n";
	my %bit = ("C"=>0, "G"=>1);
	my $o = 0;
	for (my $b=0;$b<8;$b++) {
	    my $v = $bit{substr($_, $b, 1)} << (7-$b);
	    $o += $v;
	}
	print chr($o);
    }
}
print "\n";

